/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_module;

/**
 *
 * @author SHREYASI
 */
public class Admin_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Admin_dashboard
     */
    public Admin_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        cons_db = new javax.swing.JMenu();
        new_mi = new javax.swing.JMenuItem();
        cons_details_mi = new javax.swing.JMenuItem();
        cons_pay_mi = new javax.swing.JMenuItem();
        comp_reg_mi = new javax.swing.JMenuItem();
        logout_MI = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_module/dashboard_image.jpg"))); // NOI18N

        jButton1.setText("jButton1");

        cons_db.setText("Options");

        new_mi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        new_mi.setText("New");
        new_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_miActionPerformed(evt);
            }
        });
        cons_db.add(new_mi);

        cons_details_mi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        cons_details_mi.setText("Consumer Details");
        cons_details_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_details_miActionPerformed(evt);
            }
        });
        cons_db.add(cons_details_mi);

        cons_pay_mi.setText("Consumer payments");
        cons_pay_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_pay_miActionPerformed(evt);
            }
        });
        cons_db.add(cons_pay_mi);

        comp_reg_mi.setText("Complaint Registration");
        comp_reg_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_reg_miActionPerformed(evt);
            }
        });
        cons_db.add(comp_reg_mi);

        logout_MI.setText("Logout");
        logout_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_MIActionPerformed(evt);
            }
        });
        cons_db.add(logout_MI);

        jMenuBar1.add(cons_db);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_miActionPerformed
        // TODO add your handling code here:
        New_con_account nca = new New_con_account();
        nca.setVisible(true);
    }//GEN-LAST:event_new_miActionPerformed

    private void cons_details_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_details_miActionPerformed
        // TODO add your handling code here:
        cons_details cd = new cons_details();
        cd.setVisible(true);
    }//GEN-LAST:event_cons_details_miActionPerformed

    private void cons_pay_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_pay_miActionPerformed
        // TODO add your handling code here:
        Custpay_details cpd = new Custpay_details();
        cpd.setVisible(true);
    }//GEN-LAST:event_cons_pay_miActionPerformed

    private void comp_reg_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_reg_miActionPerformed
        // TODO add your handling code here:
        Complaint_reg cr = new Complaint_reg();
        cr.setVisible(true);
    }//GEN-LAST:event_comp_reg_miActionPerformed

    private void logout_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_MIActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logout_MIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem comp_reg_mi;
    private javax.swing.JMenu cons_db;
    private javax.swing.JMenuItem cons_details_mi;
    private javax.swing.JMenuItem cons_pay_mi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem logout_MI;
    private javax.swing.JMenuItem new_mi;
    // End of variables declaration//GEN-END:variables
}
