/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_module;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.*;
import java.awt.print.*;
import javafx.print.Printer;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SHREYASI
 */
public class Calculate_bill extends javax.swing.JFrame {

    /**
     * Creates new form Calculate_bill
     */
    public Calculate_bill() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cons_id3 = new javax.swing.JLabel();
        con_id_f1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name_f1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        meter_no_f1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        units_con_f1 = new javax.swing.JTextField();
        gen_bill_b = new javax.swing.JButton();
        clear_b5 = new javax.swing.JButton();
        back_b5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        print_b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculate Bill");

        Cons_id3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Cons_id3.setForeground(new java.awt.Color(0, 51, 51));
        Cons_id3.setText("Consumer ID");

        con_id_f1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Name");

        name_f1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Meter No.");

        meter_no_f1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Units Consumed");

        units_con_f1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        gen_bill_b.setBackground(new java.awt.Color(255, 153, 0));
        gen_bill_b.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        gen_bill_b.setText("Generate Bill");
        gen_bill_b.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gen_bill_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gen_bill_bActionPerformed(evt);
            }
        });

        clear_b5.setBackground(new java.awt.Color(255, 153, 0));
        clear_b5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        clear_b5.setText("Clear");
        clear_b5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_b5ActionPerformed(evt);
            }
        });

        back_b5.setBackground(new java.awt.Color(255, 153, 0));
        back_b5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        back_b5.setText("Back");
        back_b5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_b5ActionPerformed(evt);
            }
        });

        bill.setColumns(20);
        bill.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        bill.setRows(5);
        jScrollPane1.setViewportView(bill);

        print_b.setBackground(new java.awt.Color(255, 153, 0));
        print_b.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        print_b.setText("Print");
        print_b.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cons_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(gen_bill_b, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clear_b5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(print_b, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(back_b5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(units_con_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meter_no_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(con_id_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cons_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con_id_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meter_no_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(units_con_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gen_bill_b)
                            .addComponent(clear_b5)
                            .addComponent(back_b5)
                            .addComponent(print_b))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gen_bill_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gen_bill_bActionPerformed
        // TODO add your handling code here:
        double fix_cost = 350.00; 
        double oc = 101.50;
        double puc = 0,tax = 0,total_bill = 0;
        
        int units = Integer.parseInt(units_con_f1.getText()); 
        if(units == 0)
        {
            puc = 0;
        }
        else
        {
            if(units >= 1 && units <= 100)
            {
                puc = 3.46;
            }
            else if(units >= 101 && units <= 300)
            {
                puc = 7.43;
            }
            else if(units >= 301 && units <= 500)
            {
                puc = 10.32;
            }
            else if(units >= 501 && units <= 1000)
            {
                puc = (float)11.71;
            }
            else if(units > 1000)
            {
                puc = 12.71;
            }
            tax = ((puc * units) + fix_cost + oc )*(0.16);
            total_bill = (puc * units)+ fix_cost+ oc + tax;
            }
        //bill.setText("*******************************************\n");
        bill.setText("*******************************************\n*              ELECTRICITY BILL            *\n*******************************************\n");
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date da= new Date();
        String da1 = da.toString();
        bill.setText(bill.getText()+"\n"+da1+"\n\n");
        bill.setText(bill.getText()+"Consumer ID: "+con_id_f1.getText()+"\n\n");
        bill.setText(bill.getText()+"Name: "+name_f1.getText()+"\n\n");
        bill.setText(bill.getText()+"Meter no.: "+meter_no_f1.getText()+"\n\n");
        bill.setText(bill.getText()+"Units consumed: "+units+"\n\n");
        bill.setText(bill.getText()+"Fixed charges: "+fix_cost+"\n\n");
        bill.setText(bill.getText()+"Other charges: "+oc+"\n\n");
        bill.setText(bill.getText()+"Unit rate: "+(puc*units)+"\n\n");
        bill.setText(bill.getText()+"Tax(16.00%): "+tax+"\n\n");
        bill.setText(bill.getText()+"Total amount: "+total_bill+"\n\n");
        //bill.setText(bill.getText()+"Consumer ID: "+con_id_f1.getText()+"\n\n");
    }//GEN-LAST:event_gen_bill_bActionPerformed

    private void clear_b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_b5ActionPerformed
        // TODO add your handling code here:
        con_id_f1.setText(" ");
        name_f1.setText(" ");
        meter_no_f1.setText(" ");
        units_con_f1.setText("");
        con_id_f1.requestFocus();
    }//GEN-LAST:event_clear_b5ActionPerformed

    private void back_b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_b5ActionPerformed
        // TODO add your handling code here:
        consumer_dashboard cdb3 = new consumer_dashboard();
        cdb3.setVisible(true);
    }//GEN-LAST:event_back_b5ActionPerformed

    private void print_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_bActionPerformed
        // TODO add your handling code here:
        try
        {
            bill.print();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Printer Error");
        }
    }//GEN-LAST:event_print_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculate_bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cons_id3;
    private javax.swing.JButton back_b5;
    private javax.swing.JTextArea bill;
    private javax.swing.JButton clear_b5;
    private javax.swing.JTextField con_id_f1;
    private javax.swing.JButton gen_bill_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField meter_no_f1;
    private javax.swing.JTextField name_f1;
    private javax.swing.JButton print_b;
    private javax.swing.JTextField units_con_f1;
    // End of variables declaration//GEN-END:variables
}
